name: test

on:
  workflow_dispatch:
  

jobs:
  test-setup-v4:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup dotnet 2.2.402, 3.1.404 and 3.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
           6.0.x
           8.0.x
      - name: Check tool size
        run: du -sh /Users/runner/work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh
